# Set API Keys
OPENAI_API_KEY = "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"
TAVILY_API_KEY = "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"
LANGSMITH_API = "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"
LANGCHAIN_API_KEY" "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"
